from datetime import datetime, timedelta
from typing import Protocol

from meta_loop.domain.artifacts import ArtifactRef
from meta_loop.domain.events import Event
from meta_loop.domain.task import RepositoryTarget, Task
from .models import CatalogedArtifact, CheckRunObservation, ControlEvent, FuseState, IntakeRecord, IssueIngestionRecord, Lease, PublicationEffectIntent, PublicationEffectRecord, PublicationIntent, PublicationReceipt, PublicationRecord, PreparedHead, PublicationReviewDecision, QueueCompletionResult, QueueEnqueueResult, QueueFailureResult, RunnerSessionOutcome, RunnerSessionReceipt, RunnerSessionRecord, RunnerSessionRequest, VerificationResult, WorkerResult, WorkerResultReceipt, WorkspaceRecord, WorkspaceRequest


class TaskRepository(Protocol):
    def create(self, task: Task) -> Task: ...
    def get(self, task_id: str) -> Task | None: ...
    def update(self, task: Task, expected_version: int) -> Task: ...
    def save(self, task: Task, expected_version: int) -> Task: ...
    def list(self) -> tuple[Task, ...]: ...


class EventStore(Protocol):
    def append(self, event: Event, expected_sequence: int) -> Event: ...
    def read(self, task_id: str) -> tuple[Event, ...]: ...


class TaskQueue(Protocol):
    def enqueue(self, task_id: str, priority: int, available_at: datetime, idempotency_key: str) -> QueueEnqueueResult: ...
    def claim(self, worker_id: str, now: datetime, lease_duration: timedelta) -> Lease | None: ...
    def heartbeat(self, task_id: str, worker_id: str, now: datetime, lease_duration: timedelta) -> Lease: ...
    def complete(self, task_id: str, worker_id: str, now: datetime) -> QueueCompletionResult: ...
    def fail(self, task_id: str, worker_id: str, now: datetime, error: str) -> QueueFailureResult: ...
    def recover_expired(self, now: datetime) -> tuple[QueueFailureResult, ...]: ...


class ArtifactStore(Protocol):
    def register(self, reference: ArtifactRef) -> ArtifactRef: ...
    def get(self, digest: str) -> ArtifactRef | None: ...


class ContentAddressedBlobStore(Protocol):
    def read(self, digest: str, verify: bool = True) -> bytes: ...


class CandidatePreparer(Protocol):
    def prepare(self, intent: PublicationIntent, patch: bytes) -> PreparedHead: ...


class ArtifactCatalog(Protocol):
    def register(self, artifact: CatalogedArtifact) -> CatalogedArtifact: ...
    def get(self, digest: str) -> CatalogedArtifact | None: ...
    def digests(self) -> tuple[str, ...]: ...


class Clock(Protocol):
    def now(self) -> datetime: ...


class IdGenerator(Protocol):
    def new(self) -> str: ...


class GovernanceReader(Protocol):
    def read_revision(self, revision: str): ...
    def authorize(self, revision: str, capability: str) -> bool: ...


class FuseStore(Protocol):
    def get(self) -> FuseState: ...
    def locked_get(self) -> FuseState: ...
    def set(self, state: FuseState) -> FuseState: ...


class IntakeLedger(Protocol):
    def get(self, request_id: str) -> IntakeRecord | None: ...
    def create(self, record: IntakeRecord) -> IntakeRecord: ...


class SourceIngestionLedger(Protocol):
    def reserve(self, source_key: str, trigger_event_id: str) -> None: ...
    def get(self, source_key: str) -> IssueIngestionRecord | None: ...
    def get_by_trigger_event(self, trigger_event_id: str) -> IssueIngestionRecord | None: ...
    def record_once(self, record: IssueIngestionRecord) -> tuple[IssueIngestionRecord, bool]: ...


class ControlEventStore(Protocol):
    def append(self, event: ControlEvent) -> ControlEvent: ...
    def read(self) -> tuple[ControlEvent, ...]: ...


class RunnerSessionStore(Protocol):
    def record_once(self, request: RunnerSessionRequest) -> RunnerSessionReceipt: ...
    def get(self, session_id: str) -> RunnerSessionRecord | None: ...
    def set_outcome(self, outcome: RunnerSessionOutcome) -> RunnerSessionRecord: ...


class WorkerResultLedger(Protocol):
    def record_once(self, result: WorkerResult) -> WorkerResultReceipt: ...
    def get(self, result_id: str) -> WorkerResult | None: ...


class WorkspaceManager(Protocol):
    def allocate(self, request: WorkspaceRequest, repository: RepositoryTarget, read_only: bool) -> WorkspaceRecord: ...
    def release(self, record: WorkspaceRecord) -> bool: ...


class WorkspaceLedger(Protocol):
    def record_once(self, record: WorkspaceRecord): ...
    def get(self, allocation_id: str) -> WorkspaceRecord | None: ...
    def release(self, allocation_id: str) -> WorkspaceRecord: ...


class PublicationLedger(Protocol):
    def reserve(self, intent: PublicationIntent) -> tuple[PublicationRecord, bool]: ...
    def get(self, publication_id: str) -> PublicationRecord | None: ...
    def record_prepared(self, prepared: PreparedHead, expected_version: int) -> PublicationRecord: ...
    def record_verification(self, verification: VerificationResult, expected_version: int) -> PublicationRecord: ...


class PublicationApprovalStore(Protocol):
    def append(self, decision: PublicationReviewDecision) -> tuple[PublicationReviewDecision, bool]: ...
    def read(self, publication_id: str, head_sha: str) -> tuple[PublicationReviewDecision, ...]: ...


class PublicationEffectStore(Protocol):
    def request(self, intent: PublicationEffectIntent) -> tuple[PublicationEffectRecord, bool]: ...
    def get(self, effect_id: str) -> PublicationEffectRecord | None: ...
    def reconcile(self, receipt: PublicationReceipt) -> PublicationEffectRecord: ...


class CheckRunObservationStore(Protocol):
    def append(self, observation: CheckRunObservation) -> tuple[CheckRunObservation, bool]: ...
    def read(self, publication_id: str, head_sha: str) -> tuple[CheckRunObservation, ...]: ...


class UnitOfWork(Protocol):
    tasks: TaskRepository
    events: EventStore
    queue: TaskQueue
    fuse: FuseStore
    intake_ledger: IntakeLedger
    source_ingestions: SourceIngestionLedger
    control_events: ControlEventStore
    artifacts: ArtifactCatalog
    runner_sessions: RunnerSessionStore
    worker_results: WorkerResultLedger
    workspaces: WorkspaceLedger
    publications: PublicationLedger
    publication_approvals: PublicationApprovalStore
    publication_effects: PublicationEffectStore
    check_observations: CheckRunObservationStore

    def __enter__(self) -> "UnitOfWork": ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def __exit__(self, exc_type, exc, tb) -> None: ...
